In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Full_Clean.csv")

In [3]:
df.head()

,STATE,DISTRICT,QTR,YR,NSP Male/ NewMicConfMale,NSP Female/ NewMicConf Female,NSP Total/ NewMicConf Total,Relapse Male,Relapse Female,NSN Male/NewClinDiag Male,...,35-44 yrs NSP(NewAll207+) Male,35-44 yrs NSP(NewAll207+) Female,45-54 yrs NSP(NewAll207+) Male,45-54 yrs NSP(NewAll207+) Female,55-64 yrs NSP(NewAll207+) Male,55-64 yrs NSP(NewAll207+) Female,65 & above yrs NSP(NewAll207+) Male,65 & above yrs NSP(NewAll207+) Female,SumOfHIV_Tested,SumOfHIV_infected
0,Andaman & Nicobar Islands,ANDAMAN_NICOBAR_IS,1,2008,37,21,58,5,1,20,...,8.0,2.0,3.0,1.0,2.0,0.0,2.0,2.0,0.0,0.0
1,Andhra Pradesh,ADILABAD,1,2008,257,112,369,40,21,144,...,65.0,28.0,46.0,11.0,32.0,8.0,24.0,5.0,177.0,76.0
2,Andhra Pradesh,ANANTAPUR,1,2008,529,181,710,82,12,319,...,98.0,32.0,118.0,30.0,105.0,16.0,53.0,5.0,199.0,50.0
3,Andhra Pradesh,BHADRACHALAM,1,2008,137,43,180,38,12,101,...,43.0,8.0,29.0,6.0,31.0,5.0,5.0,4.0,89.0,7.0
4,Andhra Pradesh,CUDDAPAH,1,2008,296,84,380,36,6,264,...,64.0,17.0,60.0,11.0,68.0,9.0,33.0,3.0,0.0,0.0

In [4]:
dis = df.groupby('DISTRICT')

In [378]:
cap = dis.get_group('MURSHIDABAD')

In [379]:
small = dis.get_group('Murshidabad')

In [381]:
name = pd.concat([cap , small])

In [382]:
name.to_csv(r'Downloads/TB/FINAL/Data/West Bengal/Murshidabad.csv' , index =  False)

In [14]:
name = pd.concat([name , y])

In [50]:
z = pd.concat([small[:8] , y[:2]])

In [56]:
z = pd.concat([z , small[8:10]])

In [58]:
z = pd.concat([z , small[10:14]])

In [63]:
z = pd.concat([z , small[14:18]])

In [66]:
small = pd.concat([z , y[2:]])

In [150]:
name = pd.concat([name , y])

In [141]:
state = df.groupby("STATE")

In [374]:
tamil = state.get_group('West Bengal')

In [375]:
year = tamil.groupby('YR')

In [377]:
year.get_group(2015).head(40)

,STATE,DISTRICT,QTR,YR,NSP Male/ NewMicConfMale,NSP Female/ NewMicConf Female,NSP Total/ NewMicConf Total,Relapse Male,Relapse Female,NSN Male/NewClinDiag Male,...,35-44 yrs NSP(NewAll207+) Male,35-44 yrs NSP(NewAll207+) Female,45-54 yrs NSP(NewAll207+) Male,45-54 yrs NSP(NewAll207+) Female,55-64 yrs NSP(NewAll207+) Male,55-64 yrs NSP(NewAll207+) Female,65 & above yrs NSP(NewAll207+) Male,65 & above yrs NSP(NewAll207+) Female,SumOfHIV_Tested,SumOfHIV_infected
18471,West Bengal,Alipore,1,2015,34,17,51,7,0,4,...,7.0,0.0,5.0,1.0,5.0,0.0,1.0,0.0,102.0,7.0
18472,West Bengal,Bagbazar,1,2015,29,28,57,5,2,6,...,4.0,4.0,11.0,2.0,4.0,3.0,1.0,0.0,95.0,3.0
18473,West Bengal,Bankura,1,2015,367,131,498,54,13,110,...,78.0,27.0,85.0,24.0,70.0,11.0,26.0,6.0,488.0,0.0
18474,West Bengal,Barddhaman,1,2015,768,220,988,117,33,225,...,166.0,33.0,166.0,27.0,110.0,16.0,56.0,11.0,1792.0,15.0
18475,West Bengal,Behala,1,2015,24,11,35,5,0,4,...,4.0,2.0,6.0,3.0,3.0,0.0,2.0,1.0,59.0,4.0
18476,West Bengal,Darjiling,1,2015,152,86,238,36,19,76,...,34.0,13.0,16.0,8.0,16.0,6.0,7.0,2.0,457.0,19.0
18477,West Bengal,Haora,1,2015,357,169,526,48,24,99,...,63.0,27.0,72.0,26.0,49.0,3.0,32.0,2.0,954.0,20.0
18478,West Bengal,Hazi,1,2015,29,21,50,10,6,5,...,6.0,1.0,4.0,3.0,4.0,3.0,2.0,0.0,136.0,4.0
18479,West Bengal,Hugli,1,2015,450,132,582,81,21,139,...,97.0,11.0,94.0,12.0,73.0,7.0,36.0,6.0,829.0,26.0
18480,West Bengal,Jalpaiguri,1,2015,491,200,691,91,43,140,...,82.0,28.0,90.0,16.0,63.0,10.0,38.0,8.0,1127.0,11.0
18481,West Bengal,Koch Bihar,1,2015,214,64,278,19,4,62,...,38.0,13.0,39.0,7.0,38.0,6.0,30.0,2.0,377.0,7.0
18482,West Bengal,Maldah,1,2015,386,186,572,49,14,107,...,71.0,22.0,69.0,19.0,64.0,9.0,32.0,4.0,757.0,13.0
18483,West Bengal,Maniktala,1,2015,49,23,72,8,5,7,...,15.0,4.0,5.0,1.0,5.0,1.0,4.0,0.0,152.0,9.0
18484,West Bengal,Manshatala,1,2015,38,33,71,4,4,12,...,9.0,5.0,7.0,2.0,5.0,1.0,1.0,0.0,171.0,6.0
18485,West Bengal,Medinipur East,1,2015,189,53,242,21,8,51,...,28.0,2.0,39.0,5.0,32.0,8.0,25.0,11.0,446.0,10.0
18486,West Bengal,Medinipur West,1,2015,522,178,700,62,16,187,...,119.0,30.0,131.0,30.0,96.0,24.0,41.0,10.0,1107.0,8.0
18487,West Bengal,MTMTB Boral,1,2015,39,12,51,6,0,7,...,8.0,1.0,11.0,1.0,4.0,2.0,4.0,1.0,100.0,1.0
18488,West Bengal,Murshidabad,1,2015,685,339,1024,121,27,143,...,109.0,39.0,125.0,42.0,109.0,23.0,62.0,12.0,1675.0,13.0
18489,West Bengal,Nadia,1,2015,399,108,507,75,17,57,...,63.0,20.0,73.0,10.0,80.0,14.0,51.0,5.0,816.0,17.0
18490,West Bengal,North 24 Parganas,1,2015,668,263,931,110,22,136,...,104.0,39.0,140.0,32.0,120.0,20.0,67.0,12.0,1710.0,48.0
18491,West Bengal,Puruliya,1,2015,222,82,304,39,8,143,...,38.0,15.0,39.0,10.0,37.0,4.0,21.0,5.0,545.0,3.0
18492,West Bengal,South 24 Parganas,1,2015,532,189,721,92,19,110,...,87.0,26.0,85.0,24.0,75.0,15.0,53.0,12.0,1034.0,12.0
18493,West Bengal,Strand Bank,1,2015,19,7,26,8,4,1,...,5.0,0.0,3.0,0.0,4.0,0.0,0.0,0.0,69.0,11.0
18494,West Bengal,Tangra,1,2015,52,39,91,10,7,10,...,6.0,5.0,8.0,2.0,10.0,2.0,0.0,2.0,197.0,6.0
18495,West Bengal,Tollygunge,1,2015,25,10,35,7,2,13,...,2.0,1.0,7.0,0.0,4.0,1.0,2.0,0.0,84.0,3.0
18496,West Bengal,Uttar Dinajpur,1,2015,242,99,341,36,8,57,...,49.0,12.0,37.0,13.0,42.0,7.0,16.0,1.0,544.0,13.0
18555,West Bengal,Birbhum,1,2015,374,81,455,54,10,128,...,83.0,14.0,94.0,17.0,54.0,8.0,17.0,1.0,412.0,1.0
18585,West Bengal,Dakshin Dinajpur,1,2015,223,60,283,34,2,50,...,48.0,9.0,44.0,10.0,28.0,4.0,13.0,1.0,133.0,4.0
19188,West Bengal,Alipore,2,2015,44,14,58,13,3,4,...,13.0,4.0,12.0,2.0,3.0,1.0,3.0,0.0,113.0,2.0
19189,West Bengal,Bagbazar,2,2015,47,10,57,5,2,4,...,9.0,1.0,6.0,1.0,6.0,1.0,3.0,0.0,118.0,10.0
19190,West Bengal,Bankura,2,2015,446,146,592,56,10,149,...,81.0,24.0,114.0,21.0,68.0,10.0,52.0,20.0,582.0,2.0
19191,West Bengal,Barddhaman,2,2015,875,276,1151,139,29,262,...,190.0,45.0,195.0,40.0,138.0,23.0,58.0,18.0,1932.0,22.0
19192,West Bengal,Behala,2,2015,29,8,37,3,1,2,...,5.0,0.0,7.0,0.0,6.0,2.0,2.0,0.0,77.0,4.0
19193,West Bengal,Birbhum,2,2015,539,133,672,63,11,129,...,125.0,26.0,116.0,22.0,92.0,17.0,30.0,3.0,496.0,1.0
19194,West Bengal,Darjiling,2,2015,250,111,361,47,29,92,...,44.0,16.0,43.0,20.0,23.0,6.0,12.0,3.0,673.0,23.0
19195,West Bengal,Haora,2,2015,394,159,553,58,21,111,...,79.0,19.0,80.0,10.0,51.0,7.0,22.0,11.0,1015.0,16.0
19196,West Bengal,Hazi,2,2015,39,30,69,12,5,11,...,7.0,2.0,6.0,4.0,4.0,3.0,4.0,4.0,160.0,6.0
19197,West Bengal,Jalpaiguri,2,2015,586,243,829,108,34,190,...,135.0,29.0,103.0,20.0,86.0,18.0,36.0,8.0,1609.0,11.0
19198,West Bengal,Koch Bihar,2,2015,250,87,337,26,7,75,...,42.0,10.0,43.0,8.0,62.0,11.0,34.0,7.0,312.0,3.0
19199,West Bengal,Maldah,2,2015,528,249,777,70,25,115,...,88.0,33.0,106.0,24.0,90.0,13.0,37.0,1.0,873.0,12.0

In [373]:
z = dis.get_group('Kolkota')

KeyError: 'Kolkota'

In [210]:
name = pd.concat([name , z])

In [316]:
x = name[:22]

In [322]:
y = name[22:23]

In [323]:
y['QTR'] = 3

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [324]:
y

,STATE,DISTRICT,QTR,YR,NSP Male/ NewMicConfMale,NSP Female/ NewMicConf Female,NSP Total/ NewMicConf Total,Relapse Male,Relapse Female,NSN Male/NewClinDiag Male,...,35-44 yrs NSP(NewAll207+) Male,35-44 yrs NSP(NewAll207+) Female,45-54 yrs NSP(NewAll207+) Male,45-54 yrs NSP(NewAll207+) Female,55-64 yrs NSP(NewAll207+) Male,55-64 yrs NSP(NewAll207+) Female,65 & above yrs NSP(NewAll207+) Male,65 & above yrs NSP(NewAll207+) Female,SumOfHIV_Tested,SumOfHIV_infected
15189,Uttarakhand,Hardwar,3,2013,103,63,166,38,17,50,...,18.0,7.0,17.0,6.0,14.0,4.0,8.0,2.0,218.0,2.0

In [326]:
z = pd.concat([x , y])

In [330]:
z = pd.concat([z , name[22:]])

In [337]:
name = z